version: '3.8'

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    build:
        context: ./
        dockerfile: mysql.Dockerfile
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password  
    volumes:
      - db:/var/lib/mysql
#      - ./databaseinit.sql:/docker-entrypoint-initdb.d/databaseinit.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s

     
  
volumes: 
  db:
